<?php

return [
    'europa' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec laoreet consectetur risus. Suspendisse eu nulla molestie, pellentesque metus ac, euismod nunc. Nulla sit amet tincidunt nisl, eget iaculis sapien. Mauris nunc libero, tempor eget augue euismod, pretium egestas eros. Phasellus condimentum tristique sapien in lacinia. Morbi sed commodo odio. Vestibulum ornare justo vel neque tempus, ac tincidunt neque condimentum. Etiam auctor mi massa, id fringilla nisi blandit non.',
    'asia' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec laoreet consectetur risus. Suspendisse eu nulla molestie, pellentesque metus ac, euismod nunc. Nulla sit amet tincidunt nisl, eget iaculis sapien. Mauris nunc libero, tempor eget augue euismod, pretium egestas eros. Phasellus condimentum tristique sapien in lacinia. Morbi sed commodo odio. Vestibulum ornare justo vel neque tempus, ac tincidunt neque condimentum. Etiam auctor mi massa, id fringilla nisi blandit non.',
    'africa' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec laoreet consectetur risus. Suspendisse eu nulla molestie, pellentesque metus ac, euismod nunc. Nulla sit amet tincidunt nisl, eget iaculis sapien. Mauris nunc libero, tempor eget augue euismod, pretium egestas eros. Phasellus condimentum tristique sapien in lacinia. Morbi sed commodo odio. Vestibulum ornare justo vel neque tempus, ac tincidunt neque condimentum. Etiam auctor mi massa, id fringilla nisi blandit non.',
    'america' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec laoreet consectetur risus. Suspendisse eu nulla molestie, pellentesque metus ac, euismod nunc. Nulla sit amet tincidunt nisl, eget iaculis sapien. Mauris nunc libero, tempor eget augue euismod, pretium egestas eros. Phasellus condimentum tristique sapien in lacinia. Morbi sed commodo odio. Vestibulum ornare justo vel neque tempus, ac tincidunt neque condimentum. Etiam auctor mi massa, id fringilla nisi blandit non.',
    'oceania' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec laoreet consectetur risus. Suspendisse eu nulla molestie, pellentesque metus ac, euismod nunc. Nulla sit amet tincidunt nisl, eget iaculis sapien. Mauris nunc libero, tempor eget augue euismod, pretium egestas eros. Phasellus condimentum tristique sapien in lacinia. Morbi sed commodo odio. Vestibulum ornare justo vel neque tempus, ac tincidunt neque condimentum. Etiam auctor mi massa, id fringilla nisi blandit non.',
];
